// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import BoardAtomController from './board_atom_controller.js'
import ShipAtomController from './ship_atom_controller.js'

application.register('board-atom', BoardAtomController)
application.register('ship-atom', ShipAtomController)
